/*
 * This source file was generated by the Gradle 'init' task
 */
package com.craftinginterpreters.lox;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LoxTest {
    @Test void LoxHasAScanner() {
        Lox classUnderTest = new Lox();
        assertNotNull(classUnderTest);
    }
}



